# Generated by Django 2.0.5 on 2018-05-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('introduction', models.TextField()),
                ('building', models.CharField(max_length=15)),
                ('floor_number', models.IntegerField(default=0)),
            ],
        ),
    ]
